name: 'Bot Setup'
description: 'Performs all common setup steps for bot workflows, including token generation, git config, and dependency installation.'

inputs:
  bot-app-id:
    description: 'The ID of the GitHub App.'
    required: true
  bot-private-key:
    description: 'The private key of the GitHub App.'
    required: true
  opencode-api-key:
    description: 'The default API key, used for providers that do not have one defined in the custom providers JSON.'
    required: false
  opencode-model:
    description: 'The main model to use (e.g., openai/gpt-4o or a custom one from custom providers JSON).'
    required: true
  opencode-fast-model:
    description: 'Optional: The fast model for smaller tasks.'
    required: false
  custom-providers-json:
    description: 'Optional: A JSON string defining custom providers. Use minifier to correctly format.'
    required: false

outputs:
  token:
    description: "The generated GitHub App token."
    value: ${{ steps.generate_token.outputs.token }}
  fallback-models:
    description: "Comma-separated list of models in priority order for fallback rotation"
    value: ${{ steps.export_fallbacks.outputs.models }}

runs:
  using: "composite"
  steps:
    - name: Generate GitHub App Token
      id: generate_token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ inputs.bot-app-id }}
        private-key: ${{ inputs.bot-private-key }}

    - name: Configure Git for Bot
      shell: bash
      env:
        GH_TOKEN: ${{ steps.generate_token.outputs.token }}
      run: |
        git config --global user.name "masusenseibot-agent[bot]"
        git config --global user.email "${{ inputs.bot-app-id }}+masusenseibot-agent@users.noreply.github.com"
        git config --global url."https://x-access-token:${{ steps.generate_token.outputs.token }}@github.com/".insteadOf "https://github.com/"

    - name: Generate OpenCode Configuration
      shell: bash
      env:
        # Pass inputs as environment variables to avoid shell parsing issues
        INPUT_MAIN_MODEL: ${{ inputs.opencode-model }}
        INPUT_FAST_MODEL: ${{ inputs.opencode-fast-model }}
        INPUT_DEFAULT_API_KEY: ${{ inputs.opencode-api-key }}
        INPUT_CUSTOM_PROVIDERS: ${{ inputs.custom-providers-json }}
      run: |
        set -e # Exit immediately if a command fails

        # --- HARDCODED TOGGLE ---
        # Set to "true" to add 'reasoning_effort: "high"' to the main model's request body.
        # Set to "false" to disable.
        ADD_REASONING_EFFORT="true"

        mkdir -p ~/.config/opencode

        # --- INPUTS (from environment variables, safely passed by GitHub Actions) ---
        MAIN_MODEL="${INPUT_MAIN_MODEL}"
        FAST_MODEL="${INPUT_FAST_MODEL}"
        DEFAULT_API_KEY="${INPUT_DEFAULT_API_KEY}"
        CUSTOM_PROVIDERS="${INPUT_CUSTOM_PROVIDERS}"

        # --- DEBUG: Show input lengths to diagnose secret misconfiguration ---
        echo "DEBUG: MAIN_MODEL length: ${#MAIN_MODEL} chars"
        echo "DEBUG: MAIN_MODEL first 30 chars: ${MAIN_MODEL:0:30}..."
        echo "DEBUG: CUSTOM_PROVIDERS length: ${#CUSTOM_PROVIDERS} chars"
        echo "DEBUG: CUSTOM_PROVIDERS is set: $( [ -n "$CUSTOM_PROVIDERS" ] && echo 'yes' || echo 'no' )"

        # Validate MAIN_MODEL format (should be provider/model, not JSON)
        if [[ "$MAIN_MODEL" == "{"* ]] || [[ "$MAIN_MODEL" == '"{'* ]]; then
          echo "::error::OPENCODE_MODEL secret appears to contain JSON instead of a model string like 'antigravity/claude-sonnet-4-5'. Please check your repository secrets."
          echo "::error::Expected format: provider/model (e.g., 'openai/gpt-4o' or 'antigravity/claude-sonnet-4-5')"
          echo "::error::The JSON content should be in CUSTOM_PROVIDERS_JSON secret, not OPENCODE_MODEL."
          exit 1
        fi

        # If the input was empty (or just whitespace), the variable will be empty. Set a default.
        if [ -z "$CUSTOM_PROVIDERS" ] || [ "$CUSTOM_PROVIDERS" = "" ]; then
          CUSTOM_PROVIDERS='{}'
          echo "DEBUG: CUSTOM_PROVIDERS was empty, using default: {}"
        else
          echo "DEBUG: CUSTOM_PROVIDERS has content"
        fi

        # --- INITIAL CONFIG SETUP ---
        mkdir -p ~/.config/opencode
        CONFIG='{"$schema": "https://opencode.ai/config.json", "username": "masusenseibot-agent", "autoupdate": true}'

        # Merge custom provider definitions if they are not the empty default
        if [ "$CUSTOM_PROVIDERS" != "{}" ]; then
          echo "Custom provider definitions found. Merging into configuration."
          CONFIG=$(jq --argjson customProviders "$CUSTOM_PROVIDERS" '. * {provider: $customProviders}' <<< "$CONFIG")
        else
          echo "No custom provider definitions supplied."
        fi

        # --- MODULAR FUNCTION TO CONFIGURE A MODEL ---
        configure_model() {
          local model_string="$1"
          local config_key="$2"
          local provider="${model_string%%/*}"
          local model_name="${model_string#*/}"

          # echo "--- Configuring ${config_key} with '${model_string}' ---"

          # Check if the provider exists in the custom definitions
          if jq -e --arg provider "$provider" '. | has($provider)' <<< "$CUSTOM_PROVIDERS" >/dev/null; then
            echo "Provider found in custom definitions."

            # CASE 2: Provider exists, but the model does not. This is an error.
            if ! jq -e --arg provider "$provider" --arg modelName "$model_name" '.[$provider].models | has($modelName)' <<< "$CUSTOM_PROVIDERS" >/dev/null; then
              echo "::error::Configuration error: Provider is defined, but model is not found within it. Aborting."
              exit 1
            fi

            # CASE 1: Provider and model both exist. Use it as is.
            # echo "Model '$model_name' also found. Setting '${config_key}' to '${model_string}'."
            CONFIG=$(jq --arg key "$config_key" --arg val "$model_string" '.[$key] = $val' <<< "$CONFIG")

          else
            # CASE 3: Provider does not exist in custom definitions. Treat as a standard provider.
            echo "Provider not found in custom definitions. Configuring as a standard provider."

            CONFIG=$(jq --arg key "$config_key" --arg val "$model_string" '.[$key] = $val' <<< "$CONFIG")

            echo "Setting default API key for provider."
            CONFIG=$(jq \
              --arg provider "$provider" \
              --arg apiKey "$DEFAULT_API_KEY" \
              '.provider[$provider].options.apiKey = $apiKey' <<< "$CONFIG")

            if [[ "$config_key" == "model" && "$ADD_REASONING_EFFORT" == "true" ]]; then
              echo "Reasoning effort toggle is ON. Applying to standard provider model."
              CONFIG=$(jq \
                --arg provider "$provider" \
                --arg modelName "$model_name" \
                '.provider[$provider].models[$modelName].options.reasoningEffort = "high"' <<< "$CONFIG")
            fi
          fi
        }

        # --- EXECUTION ---
        configure_model "$MAIN_MODEL" "model"
        if [ -n "$FAST_MODEL" ]; then
          configure_model "$FAST_MODEL" "small_model"
        fi

        # --- FINALIZATION ---
        echo "$CONFIG" > ~/.config/opencode/opencode.json
        # echo "--- Generated OpenCode Configuration ---"
        # jq . ~/.config/opencode/opencode.json
        # echo "----------------------------------------"
        echo "Successfully generated OpenCode configuration."

    - name: Export Fallback Models List
      id: export_fallbacks
      shell: bash
      env:
        INPUT_MAIN_MODEL: ${{ inputs.opencode-model }}
        INPUT_CUSTOM_PROVIDERS: ${{ inputs.custom-providers-json }}
      run: |
        # Extract provider and model name from the main model string
        PROVIDER="${INPUT_MAIN_MODEL%%/*}"
        MODEL_NAME="${INPUT_MAIN_MODEL#*/}"
        
        echo "DEBUG: Main model: $INPUT_MAIN_MODEL"
        echo "DEBUG: Provider: $PROVIDER"
        echo "DEBUG: Model name: $MODEL_NAME"
        
        # If no custom providers configured, just output the main model
        if [ -z "$INPUT_CUSTOM_PROVIDERS" ] || [ "$INPUT_CUSTOM_PROVIDERS" = "{}" ]; then
          echo "No custom providers configured. Using only primary model."
          echo "models=$INPUT_MAIN_MODEL" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        # Check if the provider exists in custom providers
        if ! echo "$INPUT_CUSTOM_PROVIDERS" | jq -e --arg provider "$PROVIDER" 'has($provider)' >/dev/null 2>&1; then
          echo "Provider '$PROVIDER' not found in custom providers. Using only primary model."
          echo "models=$INPUT_MAIN_MODEL" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        # Get all models for this provider, sorted by priority (lower = higher priority)
        # Models without priority field default to 999 (tried last)
        # Exclude the primary model from fallbacks since it's always first
        FALLBACKS=$(echo "$INPUT_CUSTOM_PROVIDERS" | jq -r --arg provider "$PROVIDER" --arg primary "$MODEL_NAME" '
          .[$provider].models // {}
          | to_entries
          | map(select(.key != $primary))
          | sort_by(.value.priority // 999)
          | map($provider + "/" + .key)
          | join(",")
        ')
        
        # Primary model first, then fallbacks in priority order
        if [ -n "$FALLBACKS" ]; then
          MODELS_LIST="${INPUT_MAIN_MODEL},${FALLBACKS}"
          echo "Fallback models configured: $FALLBACKS"
        else
          MODELS_LIST="$INPUT_MAIN_MODEL"
          echo "No fallback models available for provider '$PROVIDER'"
        fi
        
        echo "models=$MODELS_LIST" >> $GITHUB_OUTPUT
        echo "Model rotation order: $MODELS_LIST"

    - name: Check for Python requirements file
      id: check_requirements_file
      shell: bash
      run: |
        if [ -f requirements.txt ]; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Set up uv
      if: steps.check_requirements_file.outputs.exists == 'true'
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
        cache-dependency-glob: "requirements.txt"

    - name: Set up Python with uv
      if: steps.check_requirements_file.outputs.exists == 'true'
      shell: bash
      run: |
        uv python install 3.12
        uv venv --python 3.12

    - name: Install dependencies
      if: steps.check_requirements_file.outputs.exists == 'true'
      shell: bash
      run: |
        source .venv/bin/activate
        uv pip install -r requirements.txt

    - name: Install opencode
      shell: bash
      run: curl -fsSL https://opencode.ai/install | bash

    - name: Ensure opencode directory exists
      shell: bash
      run: mkdir -p /home/runner/.local/share/opencode/project
